config:
  user:
    name: "Luiz G."
  socials:
    - link: "https://github.com/luiztapioca"
      icon: "mdi:github"
    - link: "https://linkedin.com/in/luiztapioca"
      icon: "mdi:linkedin"
    - link: "https://bool.tec.br/blog"
      icon: "mdi:pencil-box"
  site:
    title: "Portf√≥lio"
    description: "Desenvolvido usando AstroJS e TailwindCSS."