config:
  user:
    name: "Username"
  socials:
    - link: "https://github.com/username"
      icon: "mdi:github"
    - link: "https://linkedin.com/in/username"
      icon: "mdi:linkedin"
  site:
    title: "Portfolio"
    description: "Desenvolvedor backend."