config:
  user:
    name: "Username"
  socials:
    - link: "https://github.com/username"
      icon: "mdi:github"
    - link: "https://linkedin.com/in/username"
      icon: "mdi:linkedin"
    - link: "https://bool.tec.br/blog"
      icon: "mdi:pencil-box"
  site:
    title: "Portfolio"
    description: "Desenvolvido usando AstroJS e TailwindCSS."